services:
  flask:
    build: ./src
    container_name: flask
    restart: always
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"